---
editor: 
  markdown: 
    wrap: 72
---

# Additional References

This section includes a ["What to expect"](#what-to-expect) guide, a
[Volunteer Glossary](#volun-glossary), and some bonus [lifting
techniques](#lifting). We could place some more info here as needed.

## What to expect on MACE surveys {#what-to-expect}

**What we’ll be doing**

We will be conducting an acoustic-trawl survey to determine the
abundance of midwater fish aggregations (primarily walleye pollock).
These data are critical to Gulf of Alaska or Eastern Bering Sea stock
assessment models for determining commercial fisheries quotas.

During surveys we run parallel transects along which acoustic data are
collected, and periodically trawl (up to 2-3 times a shift) to determine
species composition, length distribution, age, etc. of the fish or
invertebrates in the observed aggregations. Your main responsibility
will be helping with the processing of the trawl catch during your
shift - don’t worry, we’ll teach you everything you need to know.

**Shifts and general at-sea life**

We work around the clock in 12 hr shifts (usually 0400-1600 or
1600-0400). The crew is mainly on noon-midnight and midnight-noon
shifts, so not only are people sleeping onboard the ship at all times,
everyone’s breakfast/lunch/dinner are different meals! You may see
someone drinking a cup of coffee, bleary-eyed at 1500 hrs. While we come
onboard to work for a few weeks or months at a time, the ship is home to
the crew. Be aware of where you leave your gear and how much noise you
make in this context.

We share staterooms, and we try to assign roommates based on opposite
shifts. You will most likely not be able to access your room while you
are on shift if your roommate is off shift/sleeping. Pro tip: Plan to
have a knapsack or bag that you take with you when you leave your
stateroom that is loaded up with any items (think: chargers, iPads) or
extra clothes, tea, snacks, etc. you might want during your shift.

Typically there are 1-2 trawls to process per shift and processing a
trawl takes \~2-3 hours each. There is usually down time on each shift,
so plan accordingly (e.g., bring extra work, extra books, etc.).

If you have questions about any of this, start by asking your fish lab
colleagues onboard ship or by emailing abigail.mccarthy\@noaa.gov. If
you feel unsafe or threatened in any way, immediately talk to the
science team lead (FPC).

**What to pack**

When packing think about: Volume: while it’s tempting to pack a lot, you
are able to do laundry (see below) and have limited storage space in
your shared stateroom Function: You want to be warm and comfortable, and
have clothes that can get dirty/stinky Durability: Ships move, stuff
falls over (depending on the weather, a lot). Bring nothing fragile What
is critical: Sometimes your bags don’t make it, and the ship leaves
anyway. You can, of course, shop (noting that Dutch Harbor doesn’t have
much). Be sure to put any prescription meds, critical clothing, etc in
your carry-on bag

Linens (sheets/blanket/towels) and pillows are provided. You’ll usually
get a single bath towel, one hand towel, and one wash cloth. Quality can
vary. Pro tip: If you have specific needs or are particular, plan to
bring items with you (noting this will add to your overall gear)

During the summer cruises, you’ll want to pack for \~50°F weather
outdoors. Inside it’s obviously warmer, but most folks still wear jeans
and fleeces (and sometimes even vests) while they are indoors. The fish
processing lab is enclosed and out of the weather but can get cold.
Raingear/boots/gloves are provided. There is a small ship store with
some clothing and other items on board but be prepared to be away from
shore with no full service stores for \~3 weeks. Pro tip: There is
something special about the smell of a fish lab, and sometimes it stays
in your clothes. Consider bringing an “at-sea” sweatshirt or fleece as
an option to wear in addition to, or instead, of the raincoat in the
fish lab.

There are washing machines and dryers available to wash laundry during
calmer weather. During the summer, that typically means most days you
will be able to do laundry. During the winter, there may be days when
rough sea state closes (“secures”) the laundry. Pro tip: have a bag
large enough to carry your laundry to/from the laundry room and, if you
do laundry during your shift, to store it until you have access to your
stateroom Pro tip: Always set a timer when you put a load in the washer
or dryer. Demand for the machines can be fierce, and you’ll find your
load in a basket (wet or dry) if you forget

Survival suits, life vests, work vests, etc. will be provided aboard the
ship. We’ll also provide raingear and boots for you, and a personal
locator beacon. Be sure to let the FPC know about your sizes before the
survey starts.

*Mandatory items to bring*

Positive attitude and lots of patience Our plans change, stuff breaks,
and decisions might need to be made on-the-fly Curiosity about the
operations, the ship, and the creatures we catch Willingness to ask
questions, ask for help, get lost looking for things, ask for reminders
(about meals, etiquette, etc) Close-toed shoes are required everywhere
on the ship, except your stateroom A warm hat (required) and perhaps a
coat and gloves for weekly abandon ship drills or forays out onto the
deck Personal hygiene items (shampoo, toothbrush, deodorant, etc.) If
you’re a light sleeper bring earplugs or noise-canceling headphones
Enough prescription medication to last the cruise duration plus travel
time (\~4 weeks in summer) Clothes you don’t mind getting dirty or
damaged (e.g. fishy, salty, greasy)

*Suggested items to bring*

Motion-sickness medication; this is available from the ship's medical
officer if needed but it can be smart to bring your own Pro tip: If you
are trying a new medication, consider testing it ahead (i.e. on land) to
ensure that it does not cause any unwanted side effects Pro tip: Start
taking your meds the night before we sail, don’t wait until the weather
gets rough. Sea-sickness meds make most people sleepy, so take them an
hour or so before you want to get to sleep. Books (or other portable
devices/hobbies or things to pass the time) for down time; there is a
small collection of books on the ship but the selection is limited.
There is also a lounge with TV and a large number of movies from the
Navy’s rotating collection to watch, and the ship can have satellite TV
reception Phone, laptop, iPad, Kindle, camera, alarm clock, etc Work-out
clothes (there is exercise equipment – i.e. treadmill, stationary bike,
free weights, aboard the ship) Flip-flops for the shower (personal
preference). Closed toed shoes are required everywhere else on the ship
A set of clothes/shoes/gear for when you’re on shore (i.e., hiking
boots, day pack, etc.), especially if you’re spending extra time before
or after the cruise. A rain jacket to wear off the boat around town -
even in summer it is often cold and rainy, and you won’t want to use the
fish lab gear around town Pocket knife (don’t put this in your carry-on
bag) Sunscreen (you need sunscreen even on cloudy days) A coffee mug
(they are available on the boat, but are small) A water bottle can also
be nice, reduces the cups/glasses the stewards need to wash Personal
survival/ditch kit or extra supplies. These can be extensive (ask MACE
members about whether they have one of these) or as simple as an extra
hat and gloves that you stash with your immersion suit

**Food**

The galley is cafeteria style self-serve from the prepared options and
includes a salad bar and usually a dessert at each meal. There is also
an ice cream freezer and usually snacks like nuts or chips available
between meals. Fruit is also usually available but the quality generally
decreases as the cruise progresses.

Let the Field Party Chief know if you have any allergies or dietary
restrictions prior to the start of the survey Pro tip: Introduce
yourself to the Chief Steward so they know who you are and your dietary
needs. Thank them!!

Coffee (pretty decent, also an espresso machine) is provided. A variety
of teas is also available. The Mess Deck has a fizzy water dispenser.
Pro tip: If you have any special blends, bring them

The galley doesn’t put all available food out at once so some things may
come and go during the cruise. Before sailing, we recommend perusing the
galley, and then going to the store before the ship sails to buy
“comfort” food items and/or snacks/drinks (i.e. chocolate, bubbly water,
special type/flavor of yogurt) that you can’t live without. Pro tip:
Alaska prices can be higher, and variety might be more limited than you
may be used to, so consider bringing along your favorite “can’t live
withouts”

Note that some staterooms may have fridges, but those won’t be
accessible to you when you’re on shift (and your roommate is sleeping).
The galley often allows small items (i.e. in size and quantity) to be
labeled and stored below the salad bar, but those items are vulnerable
to unscrupulous usage by others on board! If you’ve read this far, ask
Abigail about the time someone stole an egg. Pro tip: Each day, bring
(small) items down to store in the common fridge spaces. Make sure they
are labeled!

If you are on the night shift, be sure to ask the galley to save you a
plate of food from the daytime meals (mealtimes are generally at 7am,
11am, and 5pm) so that you’ll have food around during your shift. – -
Pro tip: There will be a sign-up board for meals. Ask the Stewards about
timing for signing up, how to let them know about preferences, etc

**Communications**

You’ll have access to email, VOIP (if internet is good), and satellite
phone calls for emergencies. The Dyson has Starlink so the internet has
generally been fast as of late, even to the point of allowing streaming,
but a few years ago they maxed out their monthly allotment and we got
throttled back until the end of the month. Hopefully that doesn’t happen
again.

Before sailing, it’s good practice to log into your Gmail/Google on any
computers you plan to use for email to maximize options for 2-factor
authentication. Pro tip: Always bring printouts of your 2-factor codes,
just in case Don’t forget your yubi key or CAC card

Depending on the ship’s IT needs, the ship’s ET may connect personal
laptops and cell phones to the WiFi. You can find the ET in their office
on the same deck as the science staterooms and ask them to connect your
device to the internet when they’re available.

In Kodiak, there should be cell service for all major providers. In
Dutch, all bets are off and we typically rent a single cell phone for
the field party to share.

**Nautical phrases and ship lingo**

[common
phrases](https://oceanservice.noaa.gov/navigation/nautical-terms.html)

[seaspeak](https://oceanservice.noaa.gov/facts/seaspeak.html)

## Volunteer Glossary {#volun-glossary}

Glossary of Roles and Terms Relevant to MACE surveys aboard NOAA Ships A
non-exhaustive list of people, places and things relevant to surveys on
the NOAA ship Oscar Dyson.

### People

**NOAA Corps** - Commissioned Officer Corps, one of eight federal
uniformed services of the United States, and operates under the National
Oceanic and Atmospheric Administration. Always dressed in navy blue when
at sea. Serve \~2 year billets alternately at sea or land based
assignments.

-   **CO**- Commanding Officer, captain of the ship and person
    responsible for all matters pertaining to safety, management,
    operations, and physical condition of the ship and makes the final
    call on all decisions affecting the ship and crew
-   **XO**- Executive Officer, second in command after the CO.
    Responsible for resource management by overseeing ship personnel,
    materials, and budget.
-   **Ops**- Operations Officer, Serves as liaison between science party
    and CO and thus serves as the primary point of contact between the
    science party and ship, coordinates day to day operations between
    the science party and ship.
-   **Nav**- Navigations Officer, in charge of safe navigation and
    completion of appropriate route planning
-   **Ensign**- Junior officer, relatively new to the ship and has
    limited survey experience
-   **MPIC**- Medical Person In Charge, a member of the NOAA corps with
    extra medical training who can provide seasickness meds and who can
    consult a physician on call to provide other medication if needed.
-   **OOD**- Officer on Duty/Deck, an Officer who is in charge of the
    ship for the day or watch

**Civilian crew** - non-commissioned civilian crew members that are
either “permanently” assigned to the ship or are in the augment
(rotational) pool for NOAA ships.

-   **Chief Stew(ard)**- Head cook, Prepares menu and meals and ensures
    provisions are secured for surveys. Stationed in the galley, good
    person to know and be in good rapport with! Oversees the Steward or
    2nd Cook.
-   **2nd Cook** - Assists Chief Steward!
-   **Chief Engineer** - Lead engineer, in charge of all the moving
    parts of the ship that aren’t nets. Oversees the 1st Engineer, 2nd
    Engineer, 3rd Engineer, and General Vessel Assistant (GVA, or
    “Wiper”).
-   **Chief ET** - Ship’s electronics technician responsible for keeping
    all the ship’s computers and electronic equipment functioning. The
    person that connects personal devices to the ship's Wi-Fi and keeps
    us connected to the rest of the world when at sea.
-   **Chief Boatswain (Bo’sun)**- In charge of fishing and deck
    operations including any over the side activities (CTD’s, small boat
    deployments and usage, mooring deployments, etc.), almost always
    leads fishing operations during the day. With Lead Fishermen,
    oversees the Deck Crew.
-   **Lead Fisherman** - Leads fishing ops during the 2nd shift, second
    in charge of deck operations after the Bo’sun, not the same person
    as the Chief Bo’sun! With the Chief Bo’sun, oversees the Deck Crew.
    Senior Survey Tech- Maintains the scientific seawater sampling
    system and other tools used during fishing operations. Survey techs
    also help during trawling and over the side operations. In charge of
    verifying cleanliness of wet lab at end of survey. Oversees the
    Survey Tech.

**Science crew** - civilian NOAA employees (primarily) in charge of the
scientific operations.

-   **Chief Scientist (CS) or Field Party Chief (FPC)** - Science
    leader, in charge of science decision-making during this survey.
-   **Night cave** - Science lead from 4pm to 4am, makes fishing and
    survey-related choices and assists the FPC.
-   **Wet lab leads** - Day and night wet lab leads are in charge of
    fish processing and setting up the camtrawl and the SBE prior to
    trawling. They’re situated in the chem lab when not processing fish
    in the wet lab.
-   **ET/IT** - MACE’s electronics and software tech. Troubleshoots
    problems with the echosounder, CLAMs, and MACE’s analysis software.

### Specific places

-   **Flying Bridge**- Located outside, atop the bridge. Many of the
    officers want people to ask permission to spend time up here. Even
    if they don’t, it’s a good idea to tell someone you’re going up.
    Bridge- This is the uppermost interior deck, immediately below the
    flying bridge. This is the place where the ship’s navigation,
    steering, and trawling operations take place. Nobody calls the
    bridge the 03 deck, even though that seems like it makes sense. You
    are welcome to visit the Bridge, except when the ship is leaving the
    dock or docking, or if you are asked to leave.
-   **02 (oh-two) deck**- The deck where the CO, XO, some of the other
    officers, and the Chief Scientist have their staterooms. Also where
    the hospital and XO’s office are located. Up one ladder (stairs on
    ships are called ladders!) from the 01 deck.
-   **01 (oh-one) deck**- The deck where the science staterooms and the
    lounge are.
-   **Main deck**- Where the Fish Lab, Chem Lab, and Acoustics Lab (or
    “Cave”) are located. This could be called the 1 deck.
-   **Mess Deck**- This is where the crew eat, not to be confused with…
-   **Galley**- This is where the stewards do the cooking.
-   **Fish Lab- Aka wet lab**- location where we in MACE process the
    catch
-   **Chem Lab** - Adjacent to the fish lab, has two MACE computers set
    up, chemicals are stored there and there’s a hood in there also.
-   **Cave- Aka the Acoustics Lab**- this is where the MACE science team
    monitors the acoustics and makes decisions about trawling. We also
    work with the incoming data from here. It’s where you’ll find the
    Chief Scientist, Night Cave, and ET/IT unless they are fishing,
    eating, or sleeping.
-   **Hero Deck aka Side Sampling Station or Ops Deck**- located outside
    on the starboard side of the Chem Lab, this is where “side ops” are
    done. When we lower something that isn’t a trawl over the side of
    the ship, it goes in the water here. 2 deck- The deck below the main
    deck where crew staterooms, laundry, the gyms, and the engine room
    are all located.
-   **Forward gym**- small gym where treadmill, some weights, and rowing
    machine are located.
-   **Aft gym- aka iron gym**- shares space with the wire room where the
    huge winches that operate the trawls are located. This gym has more
    weights, and it is very loud down there while fishing operations are
    happening.
-   **Laundry room**- located down the ladderwell just forward of the
    starboard forward hatch in the mess deck.

### General places

-   **Trawl alley and trawl ramp**- At the back (aft) of the ship, where
    the trawl is deployed.
-   **Ladderway**- Stairs on a ship.
-   **Passageway**- Hallway on a ship.
-   **Gangway**- Mobile bridge used to embark and debark the vessel.
-   **Head**- bathroom on a ship.
-   **Weather deck/decks** - Decks that are open to weather, often
    secured during heavy seas/heavy freezing spray/other extreme weather
    conditions.
-   **Port/Starboard** - Port is the left side when you’re facing the
    bow (the pointy end in front) of the ship, and starboard is the
    right side. These terms help mariners avoid confusion about left &
    right, because they remain fixed regardless of which way the mariner
    faces.
-   **Stern**- Back end of a ship.

### Things you might hear (and what they mean)

-   **“All stations”**- An announcement that pertains to everyone-
    listen up!
-   **“Secure the laundry”**- Don’t use the laundry.
-   **“Secure the water”** - You probably get this by now.
-   **“Stand-by”**- Wait. Something might be happening.
-   **“This is a drill, this is a drill”** - Clearly, this is a drill,
    but what kind of drill?!? If you listen(ed) during the welcome
    aboard briefing, you’ll know that there are three kinds of drills;
    Ffire, Spill, MOB, Abandon Ship.
-   **“Dog all doors/dogs”**- This is referring to the metal latches on
    the inside of the doors that lead out to weather decks. They keep
    the doors closed and make it so the watertight seals function.
    Sadly, there are no actual dogs aboard ship.

### Gear

-   **SBE- aka “pipe bomb”**- Sea Bird Electronics instrument used to
    measure the pressure/temp/salinity/depth that we place on the head
    rope of trawl nets. Yes, it’s a terrible nickname.
-   **CTD**- Conductivity, Temperature, Depth instrument that’s deployed
    from the Hero Deck. Sometimes referred to as the CTD rosette.
-   **LFS-trawl/net**- This is the main midwater fishing net that MACE
    uses to sample the fish population, it works in tandem with the…
-   **PNE** - “Poly Nor’Eastern” net used for fishing on bottom. Is
    smaller than the midwater net and has roller gear on the footrope.
-   **83-112**- A second kind of bottom- trawl net with roller gear.
    Methot- Square-frame net designed to sample krill and other large
    zooplankton. Deployed via the trawl ramp but uses a different winch.
-   **Centerboard**- Extends
-   **Transducers aka ‘ducers or echosounders**- 18, 38, 70, 120, 200,
    and 330 kHz acoustic transducers that are mounted on the bottom of
    the ship’s centerboard and send active sound waves (pings) towards
    the bottom of the ocean.
-   **Camtrawl**- the camera system that we attach to the LFS trawl. It
    is a stereo camera, which means we can get fish lengths from it. It
    also lets us know where fish are in the water column.

## Lifting techniques {#lifting}

OSHA Proper Lifting Techniques: Safe Lifting Ergonomics
https://www.osha.com/blog/proper-lifting-techniques

Safe lifting involves:

-   Standing as close to the load as possible
-   Planting your feet shoulder-width apart with one foot slightly ahead
    of the other
-   Bending at the hips and knees only until you're deep in a squatting
    position
-   Keeping your head up and straight with your shoulders back to keep
    your back straight
-   Holding the load close to your body at waist height
-   Engaging your core muscles as you push against the ground and
    straighten your legs

Here are a few essential don'ts to keep in mind for good lifting
ergonomics:

-   Never twist your torso while lifting. Stay "nose between your toes."
-   Never lift a heavy item above shoulder level.
-   Never carry a load that obstructs your vision.
-   Never hold your breath while lifting, moving, and setting the load
    down.

As you carry the load to its destination, you want to maintain good
ergonomics. That means:

-   Holding the load as close to your body as possible, level with your
    belly button
-   Keeping your shoulders in line with your hips as you move – don't
    twist your trunk
-   Changing direction with your feet and leading with your hips
-   Taking small steps and keeping a good grip with all your fingers

Setting down a heavy object is just as dangerous as picking it up.
You'll want to reverse the lifting process, following the same ergonomic
lifting principles:

-   Keep the load close to your body and your back straight or slightly
    arched
-   Squat down, bending only at the knees and hips
-   Tighten your stomach muscles (engage your core) as you lower
    yourself
-   Kneel on one knee if necessary
