## Post Sampling and Survey Cleanup

### Post Sampling Cleanup
Cleanup during the survey does not need to be excessively thorough, however the wet lab should be rinsed off, organized and prepared for the next haul. After each haul surfaces should be sprayed down. This can be done with the overhead saltwater sprayers, the deck hose underneath the sorting table (Please do not turn the deck hose up to full pressure as this will cause excessive splashing), or the freshwater hose in the room forward of the wet lab. When spraying down the wet lab DO NOT spray the outlets located ~chest high throughout the wet lab – they can short out and/or start a fire. Pay particular attention to clearing fish and other debris from underneath the conveyor, tables and benches. 

* Rinse down the sorting bin after every haul; do not leave fish or biologicals from the previous haul in the sorting bin. It is safer and more efficient when two people work together; one person climbs the sorting bin ladder while the other person hands the hose up and adjusts the hose pressure as directed.
* Rinse away any fish, blood or other biological materials from the sorting belt, counters, shelves, floors, and discard shoot. Include the horizontal surfaces like the side of the belts, tables, and walls.
* Baskets should be rinsed and stacked along the outboard wall.
* Rinse off all knives, forceps, and styluses.
* Length boards - Again, when cleaning the length boards do not spray water directly on the clear control board area or the plugs, doing so can introduce water into the system and ruin the boards!
* Computer touch screens should be lightly rinsed with fresh water and any scales removed by wiping with a sponge. **DO NOT SCRUB COMPUTER SCREENS WITH GREEN SCRUB PADS OR OTHER ABRASVIE MATERIAL** – abrasives will scratch the screens and destroy them.
* Carefully rinse Marel scales with freshwater and sponge.


### Post Survey Cleanup
At the end of the survey the wet lab should have a thorough wash down and scrub with soap that includes all surfaces such as walls aft of the conveyor belt, outboard wall where baskets are stored, conveyor belt, discharge shoot, etc. This is a planned and collaborative effort between the Fish lab team and the Survey Techs. The abrasive scrub sponges are best for removing scales and biologicals from flat surfaces such as the walls, countertops, and other horizontal surfaces. Whereas the scrub brushes might be better for baskets etc.

* Remove all baskets, bins, floor mats, and the under counter shelving from the fish lab to the back deck. Two or more people scrub, pressure wash, and rinse gear. Return the gear to the fish lab to dry once the entire lab has been cleaned.
* Under the direction of a Survey Tech, remove the sorting belt and scrub, pressure wash, and rinse the belt on the back deck. The belt can be replaced once the sorting belt area has been thoroughly scrubbed and washed. The sorting belt will serve as a drying area for the baskets etc.
* At the end of the survey season remove any posters, materials, and paperwork from the walls so the walls can be scrubbed and washed. Between sequential surveys, it is not necessary to remove these items.
* Remove items from under the fish lab sink, scrub with a floor brush.
* Diligently scrub the walls and all surfaces of the fish lab with the abrasive scrub sponges. 2 passes might be necessary. Four to six people cleaning inside the fish lab is plenty.
* One person cleans knives, forceps, tools, ID books, posters and puts special study materials away.
* Length boards - Again, when cleaning the length boards do not spray water directly on the clear control board area or the plugs, doing so can introduce water into the system and ruin the boards!
* Computer touch screens should be lightly rinsed with fresh water and any scales removed by wiping with a sponge. **DO NOT SCRUB COMPUTER SCREENS WITH GREEN SCRUB PADS OR OTHER ABRASVIE MSATERIAL** – abrasives will scratch the screens and destroy them.
* Carefully clean Marel scales with sponge and freshwater. Remove top and allow to air dry.


