# Sampling Procedures

## Saftey and Ergonomics
Prior to beginning sampling, take time to consider physical saftey and ergonomics. There are several steps that can be taken. 

* Consider some pre sampling stretches to warm up muscles (link to GAP stretches).
* The fish lab is wet and slippery, make sure that the non-slip floor mats are placed at all workstations.
* Remember to limit basket weights to 20 kg to prevent injuries and practice safe [lifting techniques](#lifting).
* use two people to move heavy objects like the camtrawl or large totes of fish from the deck.

## Midwater or Bottom Trawl catches

### 1. Recording the catch in CLAMS

Open the Catch Logger for Acoustic Midwater Surveys (CLAMS) app; See the document CLAM Digging located in the folder `G:\CLAMS` for entering catch data on the CLAMS app.
See the latest power point document “…Table Tips” for specific survey sampling guidelines, found in the cruise folder or posted in the fish lab

### 2. Equipment Retrieval
As the net is hauled back, obtain the SBE (see section IV.A. - SBE 39 Temperature/Pressure data Midwater recorder instructions) from the deck crew and download it as soon as possible. The SBE downloader app is located on the forward computer nearest the sink. Follow the protocols. 

Rinse the CamTrawl with fresh water and if time allows download the images before the next deployment. For information on CamTrawl deployment and downloading go to the “BOC Associated Documents” folder. Staff should familiarize themselves with the “Camtrawl quick guide” procedures just in case. However, MACE IT will most often download the CamTrawl images after the haul has been processed.

It is common for other equipment to be handed over to the slime lab from the deck crew; various integrated trawl instrumentation (ITI) and special study instrumentation (light sensors, etc.).

### 3. Splitter Bin Versus Sorting Table
Catches with a total catch weight of less than ~ 2,000 kg (2 tons) can be dumped directly into the sorting table (link to that section) However, for larger catches (>2,000 kg) they must first go into a deck “splitter” bin and are “split” for a subsample. 

### Splitter Bin

* For split catches, a total catch weight must be obtained by weighing the catch in the codend. The load cell(provide link to instructions) or the crane scale may be used. Each (?) crane has an internal scale that has a readout both at the crane and in the fish lab. However the crane scales and/or the readout in the fish lab is not always reliable. A weight from the load cell is preferred. 

* Once the load cell is secure and hanging from the crane hook press TARE and you are ready to weigh the codend. 

* After the codend is weighed and recorded the catch is dumped into the deck “splitter” bin. 

* Next the the weight of the empty codend should be recorded. 

* A cargo (brailer) net attached to a metal frame in the bottom of the splitter bin is used to collect a subsample of the catch. This subsample is then lifted into the sorting table. 

* Once the crane is secure, wear PPE and receive deck permission to check the sorting table and splitter bin to make sure the catch is representative/homogenous. 

* The total catch weight is the difference of the full codend and the weight of the empty codend. The load cell can output in either pounds or kilograms. Make sure the load cell reads in kilograms, otherwise select the pounds unit in CLAMS.

**Splitter Tips**

* If getting weights from the load cell on deck, checking the splitter bin, or checking the sorting table make sure you are wearing PPE (helmet + floatation, either a float coat or life jacket)! Also make sure the deck crew know you are out there.

* Deleted a not about using Whole Haul here. I think the practice of doing that is discouraged. maybe want to double check that whole haul sampling for a single species is described somewhere for example in case of a shark.  

* If the total catch exceeds the capacity of the deck “splitter” bin and the catch is not homogenous, splits should be repeated (with subsequent emptying of the bin) until the entire codend is empty. Alternately, the end of the codend has been pinched off at the thick strap and placed into the sorting table and the rest of the catch dumped overboard. This is not ideal but has happened due to excessive catch, poor weather conditions, and inexperienced crew preventing safe splitter bin operations.

## Slime Line
The catch from the sorting table flows directly onto the 'slime line' though a hydraulic door. 




## Lifting techniques {#lifting}
OSHA Proper Lifting Techniques: Safe Lifting Ergonomics
https://www.osha.com/blog/proper-lifting-techniques

Safe lifting involves:

* Standing as close to the load as possible
* Planting your feet shoulder-width apart with one foot slightly ahead of the other
* Bending at the hips and knees only until you're deep in a squatting position
* Keeping your head up and straight with your shoulders back to keep your back straight
* Holding the load close to your body at waist height
* Engaging your core muscles as you push against the ground and straighten your legs

Here are a few essential don'ts to keep in mind for good lifting ergonomics:

* Never twist your torso while lifting. Stay "nose between your toes."
* Never lift a heavy item above shoulder level.
* Never carry a load that obstructs your vision.
* Never hold your breath while lifting, moving, and setting the load down.

As you carry the load to its destination, you want to maintain good ergonomics. That means:

* Holding the load as close to your body as possible, level with your belly button
* Keeping your shoulders in line with your hips as you move – don't twist your trunk
* Changing direction with your feet and leading with your hips
* Taking small steps and keeping a good grip with all your fingers

Setting down a heavy object is just as dangerous as picking it up. You'll want to reverse the lifting process, following the same ergonomic lifting principles:

* Keep the load close to your body and your back straight or slightly arched
* Squat down, bending only at the knees and hips
* Tighten your stomach muscles (engage your core) as you lower yourself
* Kneel on one knee if necessary
